#!/usr/bin/env bash
Who="Tim Menzies"
When=2018
What="Gawk development tools"
Awk="`which gawk`"
Vim="/usr/local/bin/vim"
Head="# vim: set filetype=awk ts=2 sw=2 sts=2 expandtab:cindent:formatoptions+=cro"

usage() { cat<<-EOF
	
	# Do this once:
	Edit the ide file, edit the first 8 lines.

	cd etc; chmod +x etc; ./etc setup

	# To call this code
	To run something:

	../etc/idea com
	
	For a list of commands, see

	../etc/ide help
	
	# If you want a handy shortcut...
	alias i="../etc/ide "
	
	EOF
}

# config. 

Ide=".."
Etc="$Ide/etc"
Docs="$Ide/docs"
Src="$Ide/src"
Tests="$Ide/tests"
Tmp="$Ide/tmp"

if [ ! -d "$Etc" ]; then 
  echo "Run this script command in a sub-directory below repository main directory"
  exit 1
fi

for d in $Docs $Tmp $Etc $Src $Tests; do
  mkdir -p $d
  if [ ! -f "$d/README.md" ]; then
    touch $d/README.md
    git add $d/README.md
  fi
done

setup1() {
  if [ ! -f "$2" ]; then $1 > $2; git add $2; fi
}
setup() { ## # setup files
 setup1 _readme    ../README.md
 setup1 _requires  ../requirements.txt
 setup1 _gitignore ../.gitignore
 setup1 _license   ../LICENSE.md
 setup1 _citation  ../CITATION.md
 setup1 _vimrc     $Tmp/vimrc
 setup1 _lib       $Src/gold.awk
}
hi() { ## # pull from repo
  git pull
}
bye() { ## # push to repo
  git commit -am 'new stuff'
  git push
  git status
}
blank() {  ## # Show an empty file
  cat<<-EOF
	$Head

	@include "gold"

EOF
}
_readme() { cat<<-EOF
	# Languagez.gawk

	[![DOI](https://zenodo.org/badge/158887786.svg)](https://zenodo.org/badge/latestdoi/158887786)

	Mapping some generic languagez tools into gawk.

	## Setup

	- **Zenodo:** need to  remove appplication restrictions at the organization level
	  https://github.com/organizations/languagez/settings/oauth_application_policy

EOF
}
_requires() { cat<<-EOF
	gawk>=4.1
EOF
}
# grab your favorite gitignore from https://github.com/github/gitignore
_gitignore() { cat<<-EOF
	tmp
	.awk
	
	## VIM STUFF
	# Swap
	[._]*.s[a-v][a-z]
	[._]*.sw[a-p]
	[._]s[a-rt-v][a-z]
	[._]ss[a-gi-z]
	[._]sw[a-p]
	
	# Session
	Session.vim
	
	# Temporary
	.netrwhist
	*~
	# Auto-generated tag files
	tags
	# Persistent undo
	[._]*.un~
EOF
}
_license() { cat<<-EOF
	# LICENSE

	Redistribution and use in source and binary forms, with or
	without modification, are permitted provided that the
	following conditions are met:
	
	1. Redistributions of source code must retain the above
	copyright notice, this list of conditions and the following
	disclaimer.
	
	2. Redistributions in binary form must reproduce the above
	copyright notice, this list of conditions and the following
	disclaimer in the documentation and/or other materials
	provided with the distribution.
	
	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
	CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
	INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
	MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
	DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
	CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
	SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
	NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
	LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
	CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
	OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
EOF
}
_citation() { 
	cat<<-EOF
	# CITATION

	Please cite this work as

	$Who, $When
	$What

	    @misc{languagez:gawk19,
	    	title  = "$What",
	    	author = "$Who",
	    	year   = "$When,
	    }
	
EOF
}
# end config
#---------------------------------
help() { ## # Show options.
  _banner
  printf "options:\n"
  grep '{ ##' $0  | sort | $Awk '
  BEGIN  {FS="#"}
  /grep/ { next}
         { gsub(/[^a-zA-Z0-9_]/,"",$1)
	   printf("  %-10s%-8s%s\n",$1,$3,$4)}'
  echo
}

_banner() { 
  red=$(tput setaf 1)
  blue=$(tput setaf 6)
  ltyl=$(tput setaf 11)
  white=$(tput setaf 15)
  tput setaf 11
  cat<<-'EOF'

	       .-"; ! ;"-.
	      .'!  : | :  !`.
	     /\  ! : ! : !  /\
	    /\ |  ! :|: !  | /\
	   (  \ \ ; :!: ; / /  )
	  ( `. \ | !:|:! | / .' )
	  (`. \ \ \!:|:!/ / / .')
	   \ `.`.\ |!|! |/,'.' /
	    `._`.\\\!!!// .'_.'
	       `.`.\\|//.'.'
	        |`._`n'_.'|  hjw
	        "----^----"	
	EOF
   cat<<-EOF

	$What
	$Who, $When

	EOF
  tput setaf 6
}
_passfail() { 
  gawk '
    BEGIN        { f = p = 0 }
                 { print $0 }
    $2=="PASSED" { p++ }
    $2=="FAILED" { f++ }
    END          { 
      print "\n# :PASSED " p " :FAILED " f \
	    " :PERCENT " int(101*p/(p+f+0.0001))
      exit FAILED > 0
    }'
}
ok() { ## STEM # Run one file. If no arg, then run all.
  if [ -z "$1" ]; then
    for f in *ok.$x; do
	    run $(basename "$f" ".$x")
    done | _passfail
  else 
    if [ ! -f "${1}ok.$x" ]; then
	echo "#E> missing ${1}ok.$x"
	return 1
    fi
    run ${1}ok | _passfail
  fi  
}
_2awk() {
  $Awk '
BEGIN {In=1}

gsub(/^\"\"\"/,"") { In =  1 - In  }
                   { pre  = In ? "" : "# " }
In {
    print pre gensub(/\.([^0-9])([a-zA-Z0-9_]*)/, 
                    "[\"\\1\\2\"]", "g", $0)
    next }
   {
    print pre $0
   }
' -
}
_lib() { cat<<-EOF
	$Head
	
	# ----------------------------------------
	# structs
	
	function List(i)     { split("",i,"") }
	
	function has(lst,key,fun) {
	  lst[key][SUBSEP]
	  split("",lst[key],"")
	  if (fun) @fun(lst[key])
	}
	function have( lst,key,fun,a) { 
	  	has(lst,key); @fun(lst[key],a) }
	function haves(lst,key,fun,a,b) { 
		has(lst,key); @fun(lst[key],a,b) }
	function have2(lst,key,fun,a,b,c) { 
		has(lst,key); @fun(lst[key],a,b,c) }
	function have3(lst,key,fun,a,b,c,d) { 
		has(lst,key); @fun(lst[key],a,b,c,d) }
	function have4(lst,key,fun,a,b,c,d,e) { 
		has(lst,key); @fun(lst[key],a,b,c,d,e) }
	
	# ---------------------------------------
	# tests
	
	function tests(what, all,   one,a,i,n) {
	   n = split(all,a,",")
	   print " "
	   print "#--- " what " -----------------------"
	   for(i=1;i<=n;i++) {
	     one = a[i]
	     @one(one)
	}}
	function is(f,got,want,    pre) {
	  if (want == "") want=1
	  if (want == got)
	    pre="#TEST:\tPASSED"
	  else
	    pre="#TEST:\tFAILED"
	  print( pre "\t" f "\t" want "\t" got )
	}
	EOF
}
_vimrc() { cat<<-EOF 
	set backupdir-=.
	set backupdir^=~/tmp,/tmp
	set nocompatible 
	filetype plugin indent on
	set modelines=3
	set scrolloff=3
	set autoindent
	set visualbell
	set backspace=indent,eol,start
	set laststatus=2
	set splitbelow
	set mouse=a
	set title
	set number
	autocmd BufEnter * silent! lcd %:p:h
	set nohlsearch
	set showmatch
	set matchtime=15
	set background=light
	set syntax=on
	syntax enable
	set ignorecase
	set incsearch
	set smartcase
	set showmatch
	colorscheme zellner
	EOF
}
ed() {
  $Vim -u "$Tmp/vimrc" $*
}
run() { ## STEM # Run STEM.au file
  prep
  file=$1
  Built="$Lib/$file.awk"
  shift
  AWKPATH=$Lib                              \
      $Awk --profile="$Tmp/${file}.profile"   \
           --dump-variables="$Tmp/${file}.vars" \
           -f $Built "$@"
  if [ -f "$Tmp/${file}.vars" ]; then
    $Awk '/[A-Z][A-Z]/ {next} {print "W> rogue local: ",$0}' $Tmp/${file}.vars
  fi
}
prep() { ##  # Ensure all .auk files have .awk version
  for i in *.$x; do
    stem=$(basename "$i" ".$x")
    j="$Lib/${stem}.awk"
    if [ "$i" -nt "$j" ]; then
      echo "# $i ==> $j"
      cat "$i" | _2awk > "$j"
    fi
  done
} 
_gitting() {
  git config --global credential.helper cache
  git config credential.helper 'cache --timeout=3600'
}
push() { ## # Commit all, push to Github
  _gitting
  git status; git commit -am "commit"; git push
}
pull() { ## # Pull from Github
  _gitting
  git pull
}
###################################
# get all the configs (if any)


if [ -f "${1}.$x" ]; then
        run "$@"
elif [ `type -t $1`"" == 'function' ]; then
        f=$1
        shift
        $f "$@"
else
     help
fi


